# Generated by Django 3.2.4 on 2021-06-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'basse'), ('medium', 'moyenne'), ('high', 'haute')], default='low', max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('to_do', 'à faire'), ('on_going', 'en cours'), ('done', 'terminé')], default='to_do', max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('bug', 'bug'), ('improvement', 'amélioration'), ('task', 'tâche')], default='bug', max_length=128),
        ),
    ]
