# Generated by Django 3.2.4 on 2021-06-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('author', 'Auteur'), ('contributor', 'Contributeur')], default='contributor', max_length=128),
        ),
    ]
