# Generated by Django 3.2.4 on 2021-06-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('projects', '0001_initial'),
        ('contribution', '0002_contributor_permission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('user', 'project')},
        ),
    ]
